<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="NSL-6388" failures="2" tests="6" name="Default test" time="224.479" errors="0" timestamp="2024-03-13T17:11:02 IST">
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyNumberOfItems" time="6.876"/>
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyNewlyAddedManagerLogEntries" time="4.258">
    <failure type="java.lang.AssertionError" message="Shift is not matched expected [PM] but found [AM]">
      <![CDATA[java.lang.AssertionError: Shift is not matched expected [PM] but found [AM]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at loungePro.testcases.DailyManagerLogTest.verifyNewlyAddedManagerLogEntries(DailyManagerLogTest.java:232)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyNewlyAddedManagerLogEntries -->
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyNewlyAddedManagerLogEntries" time="19.681"/>
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyNewlyAddedManagerLogEntries" time="19.383"/>
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyNewlyAddedManagerLogEntries" time="19.804"/>
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyNewlyAddedManagerLogEntries" time="19.929">
    <failure type="java.lang.AssertionError" message="Success msg text not matching expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: Success msg text not matching expected [2] but found [3]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at loungePro.testcases.DailyManagerLogTest.verifyNewlyAddedManagerLogEntries(DailyManagerLogTest.java:250)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyNewlyAddedManagerLogEntries -->
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyDefaultToDate" time="0.0">
    <ignored/>
  </testcase> <!-- verifyDefaultToDate -->
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyNewlyAddedManagerLogEntriesOld" time="0.0">
    <ignored/>
  </testcase> <!-- verifyNewlyAddedManagerLogEntriesOld -->
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyDefaultFromDate" time="0.0">
    <ignored/>
  </testcase> <!-- verifyDefaultFromDate -->
  <testcase classname="loungePro.testcases.DailyManagerLogTest" name="verifyDailyManagerLogEntryPageURL" time="0.0">
    <ignored/>
  </testcase> <!-- verifyDailyManagerLogEntryPageURL -->
</testsuite> <!-- Default test -->
